export const USER_REQUEST = "USER_REQUEST";
export const USER_FALIURE = "USER_FALIURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

